# This task list generates the Caddy configuration for a project
---
- name: Check if authentications are defined
  set_fact:
    auths_basic: "{{ auths_basic|default([]) + item.security.authentication }}"
  when: item.security is defined and item.security.authentication is defined
  with_items: "{{ app_config.domains }}"

- name: Generate Caddy Terraform file
  include_tasks: "{{ module_role_path|default(role_path) }}/tasks/caddy_steps/generate-serverconfig-tf.yml"

