---
- block:
    - template:
        src: "{{ module_role_path|default(role_path) }}/templates/caddy/Caddyfile.j2"
        dest: "{{ dest_file }}"
    - block:
        - slurp: src="{{ dest_file }}"
          register: slurpfile
        - debug: msg="{{ slurpfile['content'] | b64decode }}"
      when: lookup('env','TEST') == '1'
  vars:
    dest_file: "{{ caddy_root|default('/etc/caddy') }}/Caddyfile"

