---
- hosts: localhost
  connection: local
  vars:
    stackhead__roles: "~/.ansible/collections/ansible_collections/getstackhead/stackhead/roles"
  tasks:
    - include_vars: "{{ stackhead__roles }}/stackhead_module_api/testdata/variables.yml"
    - set_fact:
        containerapp__expose: "{{ containerapp__expose|default([]) + item.expose }}"
      when: item.expose is defined and item.expose not in containerapp__expose|default([])
      with_items: "{{ app_config.domains }}"
    - block:
        - name: Generate Caddy Terraform file
          import_tasks: "{{ module_role_path | default(role_path) }}/tasks/caddy_steps/generate-serverconfig-tf.yml"
        - name: Generate Caddyfile
          import_tasks: "{{ module_role_path | default(role_path) }}/tasks/caddy_steps/generate-caddyfile-tf.yml"
      vars:
        module_role_path: ".."
        caddy_root: "."
