---
- hosts: localhost
  connection: local
  tasks:
    - include_vars: "{{ stackhead__roles }}/stackhead_module_api/testdata/variables.yml"
    - set_fact:
        containerapp__expose: "{{ containerapp__expose|default([]) + item.expose }}"
      when: item.expose is defined and item.expose not in containerapp__expose|default([])
      with_items: "{{ app_config.domains }}"
    - block:
        - name: Generate Caddy Terraform file
          import_tasks: "../tasks/steps/generate-serverconfig-tf.yml"
        - name: Generate Caddyfile
          import_tasks: "../tasks/steps/generate-caddyfile-tf.yml"
      vars:
        role_path: ".."
        caddy_root: "."
